spring:
  cloud:
    gateway:
      routes:
        - id: wms-service
            uri: ${WMS_SERVICE_HOST:"http://localhost:9001"}
            predicates:
              - Path=/** # Path predicate for URI path matching
            filters:
              - PrefixPath=/api