spring:
  cloud:
    gateway:
      routes:
        - id: wms-service
            uri: "http://servicea:9001"
            predicates:
              - Path=/** # Path predicate for URI path matching
            filters:
              - PrefixPath=/api